name: Dynamic Workflows

on:
  workflow_dispatch:
    inputs:
      base_image:
        description: 'Base Image'
        required: true
        default: 'python:3.8'
      packages:
        description: 'Comma-separated packages'
        required: false
      memory:
        description: 'Memory (Mi)'
        required: true
        default: '512'
      cpu:
        description: 'CPU (cores)'
        required: true
        default: '1'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: |
        echo "FROM ${{ github.event.inputs.base_image }}" > Dockerfile
        for package in $(echo "${{ github.event.inputs.packages }}" | tr ',' '\n'); do
          echo "RUN pip install $package" >> Dockerfile
        done
        docker build -t custom-image:latest .

    - name: Deploy to Kubernetes
      run: |
        cat <<EOF > deployment.yaml
        apiVersion: v1
        kind: Pod
        metadata:
          name: custom-deployment
        spec:
          containers:
          - name: custom-container
            image: custom-image:latest
            resources:
              requests:
                memory: "${{ github.event.inputs.memory }}Mi"
                cpu: "${{ github.event.inputs.cpu }}"
              limits:
                memory: "${{ github.event.inputs.memory }}Mi"
                cpu: "${{ github.event.inputs.cpu }}"
        EOF
        kubectl apply -f deployment.yaml
