name: Build, Scan, and Push Docker Image

on:
  push:
    branches:
      - main 
jobs:
  build-scan-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/your-image-name:latest .

      - name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@v0.11.0
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/your-image-name:latest
          format: table
          exit-code: 1 
          severity: CRITICAL,HIGH 

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/your-image-name:latest
